name: marlin_auto_build
description: "Continuous automatic builds of the Marlin 3d-printer firmware"
author: "zisismaras"

branding:
  icon: "code"
  color: "green"

inputs:
  token:
    default: ${{ github.token }}
    description: "The token to use"
  repository:
    default: ${{ github.repository }}
    description: "The current repository"
  actor:
    default: ${{ github.actor }}
    description: "The user triggering the build"

runs:
  using: "composite"
  steps:
    - name: Check out current repository
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install Platformio CLI
      run: pip install -U platformio
      shell: bash

    - name: Make temp directory
      run: mkdir -p /tmp/marlin_auto_build
      shell: bash

    - name: Run build script
      run: bunx git://github.com/oskardotglobal/marlin_auto_build.git
      shell: bash
      working-directory: "/tmp/marlin_auto_build"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        GITHUB_ACTOR: ${{ inputs.actor }}

    - name: Commit and push changes
      run: |
        rm -rf dist
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "new build"
          git push
        fi
      shell: bash
